// defaults.js
var defaultValuesBasic = {
    'purchase-price': 500000,
    'closing-costs': 5000,
    'investment-years': 20,
    'home-growth-rate': 4,
    'down-payment-percent': 25,
    'im-rate': 6,
    'monthly-rent': 4500,
    'annual-rent-increase': 2,
    'annual-insurance': 2000,
    'annual-hoa': 1500,
    'annual-property-tax': 2.25,
    'annual-maintenance': 1000,
    'cpi-assumption': 2,
    'management-fee': 10
};

var defaultValuesAdvanced = {
    'purchase-price-advanced': 500000,
    'closing-costs-advanced': 2000,
    'investment-years-advanced': 20,
    'home-growth-rate-advanced': 4,
    'down-payment-percent-advanced': 25,
    'im-rate-advanced': 6,
    'monthly-rent-advanced': 4500,
    'annual-rent-increase-advanced': 2,
    'annual-insurance-advanced': 2000,
    'annual-hoa-advanced': 1500,
    'annual-property-tax-advanced': 2.25,
    'annual-maintenance-advanced': 1000,
    'management-fee-advanced': 10,
    'hel-amount': 50000,
    'hel-rate': 6,
    'hel-closing-fee': 1,
	'hel-extra-payment-times': 2,
    'hel-extra-payment-amount': 2500,
    'im-closing-fee': 1,
	'im-extra-payment-times': 2,
    'im-extra-payment-amount': 10000,
    'refinance-years': 5,
    'rm-rate': 4,
    'rm-closing-fee': 1,
	'rm-extra-payment-times': 2,
    'rm-extra-payment-amount': 2500,
    'occupancy-rate': 90,
    'annual-insurance-growth': 8,
    'annual-hoa-growth': 2,
    'property-tax-growth': 2,
    'maintenance-growth': 2,
};

var tooltipsBasic = {
    'purchase-price': "The total price at which the property is being purchased.",
    'closing-costs': "Additional costs incurred during the closing of the property purchase.",
    'investment-years': "The number of years you plan to hold the investment.",
    'home-growth-rate': "The expected annual growth rate of the property's value.",
    'down-payment-percent': "The percentage of the purchase price paid upfront.",
    'im-rate': "The annual interest rate on the mortgage loan.",
    'monthly-rent': "The expected monthly rental income from the property.",
    'annual-rent-increase': "The expected annual increase in rent.",
    'annual-insurance': "The annual cost of insuring the property.",
    'annual-hoa': "The annual cost of homeowners association fees.",
    'annual-property-tax': "The annual property tax rate.",
    'annual-maintenance': "The annual cost of maintaining the property.",
    'cpi-assumption': "The expected annual inflation",
    'management-fee': "The percentage of rental income paid for property management services."
};

var tooltipsAdvanced = {
    'purchase-price-advanced': "The total price at which the property is being purchased.",
    'closing-costs-advanced': "Additional costs incurred during the closing of the property purchase exluding loan origination fees.",
    'investment-years-advanced': "The number of years you plan to hold the investment.",
    'home-growth-rate-advanced': "The expected annual growth rate of the property's value.",
    'down-payment-percent-advanced': "The percentage of the purchase price paid upfront.",
    'im-rate-advanced': "The annual interest rate on the mortgage loan.",
    'monthly-rent-advanced': "The expected monthly rental income from the property.",
    'annual-rent-increase-advanced': "The expected annual increase in rent.",
    'annual-insurance-advanced': "The annual cost of insuring the property.",
    'annual-hoa-advanced': "The annual cost of homeowners association fees.",
    'annual-property-tax-advanced': "The annual property tax rate.",
    'annual-maintenance-advanced': "The annual cost of maintaining the property.",
    'management-fee-advanced': "The percentage of rental income paid for property management services.",
    'hel-amount': "The amount of the Home Equity Loan.",
    'hel-rate': "The interest rate of the Home Equity Loan.",
    'hel-closing-fee': "The closing fee for the Home Equity Loan.",
	'hel-extra-payment-times':"The number of times per year you pay extra for the Home Equity Loan.",
    'hel-extra-payment-amount': "The extra payment amount each year for the Home Equity Loan.",
    'im-closing-fee': "The closing fee for the Initial Mortgage.",
	'im-extra-payment-times':"The number of times per year you pay extra for the Initial Mortgage.",
    'im-extra-payment-amount': "The extra payment amount per year for the Initial Mortgage.",
    'refinance-years': "The number of years after which refinancing will be considered.",
    'rm-rate': "The interest rate of the Refinanced Mortgage.",
    'rm-closing-fee': "The closing fee for the Refinanced Mortgage.",
	'rm-extra-payment-times':"The number of times per year you pay extra for the Refinanced Mortgage.",
    'rm-extra-payment-amount': "The extra payment amount per year for the Refinanced Mortgage.",
    'occupancy-rate': "The expected occupancy rate of the property.",
    'annual-insurance-growth': "The expected annual growth rate of the insurance cost.",
    'annual-hoa-growth': "The expected annual growth rate of the HOA fees.",
    'property-tax-growth': "The expected annual growth rate of the property assessed value for tax calculation.",
    'maintenance-growth': "The expected annual growth rate of maintenance costs.",
};

// Array of keys
var keysArray = [
    'annual-hoa',
    'annual-hoa-growth',
    'annual-insurance',
    'annual-insurance-growth',
    'annual-maintenance',
    'annual-property-tax',
    'annual-rent-increase',
    'closing-costs',
    'cpi-assumption',
    'down-payment-percent',
    'hel-amount',
    'hel-closing-fee',
    'hel-extra-payment-amount',
    'hel-extra-payment-times',
    'hel-extra-payments',
    'hel-rate',
    'hel-term',
    'home-growth-rate',
    'im-closing-fee',
    'im-extra-payment-amount',
    'im-extra-payment-times',
    'im-extra-payments',
    'im-rate',
    'im-term',
    'investment-years',
    'maintenance-growth',
    'management-fee',
    'monthly-rent',
    'occupancy-rate',
    'property-tax-growth',
    'purchase-price',
    'refinance-mortgage',
    'refinance-years',
    'rm-closing-fee',
    'rm-extra-payment-amount',
    'rm-extra-payment-times',
    'rm-extra-payments',
    'rm-rate',
    'rm-term',
    'use-hel'
];
